### ISSUE TITLE
Create a simple about section for the website.

### ISSUE THREAD

**Issue by junaidzamaahmed** [BUHPHSS/BUHPHSS-Website#1]
Create a simple about section for the website. Make sure to use **proper comments** and create a different css file named about.css for the section. Please **DO NOT** overwrite existing css classes.

**Comment by AyushSarode** [comment]
Please assign me!
I can try.

**Comment by Noothan-am** [comment]
@junaidzamaahmed can I add lorem as a description?

**Comment by TanveerShahriar** [comment]
I would love to contribute.

**Comment by Noothan-am** [comment]
@junaidzamaahmed please review my pr in which I added an about section
